[build]
  publish = "website/dist"
  command = "npm i -g pnpm && pnpm install && pnpm run build --mode production"

[build.environment]
  NODE_VERSION = "14"
  NPM_FLAGS = "--prefix=/dev/null"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[[headers]]
  for = "/*"

  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    Expect-CT = 'max-age=0, report-uri="https://o425642.ingest.sentry.io/api/5363724/security/?sentry_key=cfe32af78b1a45b8b01930684aafb964"'
    Permissions-Policy = "interest-cohort=()" 
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = "default-src 'self' https://api.thesemetrics.org https://pixel.thesemetrics.org https://api.staging.thesemetrics.org https://pixel.staging.thesemetrics.org; script-src 'self' 'unsafe-eval' https://unpkg.com; style-src 'self' 'unsafe-inline'; connect-src 'self' https://api.thesemetrics.org https://pixel.thesemetrics.org https://api.staging.thesemetrics.org https://pixel.staging.thesemetrics.org https://o425642.ingest.sentry.io; object-src 'none'; report-uri https://o425642.ingest.sentry.io/api/5363724/security/?sentry_key=cfe32af78b1a45b8b01930684aafb964"
